apiVersion: v1
kind: ConfigMap
metadata:
  name: nextdmarc-backend-config
  namespace: nextdmarc
data:
  ENVIRONMENT: "staging"
  API_PREFIX: "/api/v1"
  LOG_LEVEL: "INFO"
  REDIS_URL: "redis://nextdmarc-redis:6379/0"
  CELERY_BROKER_URL: "redis://nextdmarc-redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://nextdmarc-redis:6379/2"
  ELASTICSEARCH_URL: "http://nextdmarc-elasticsearch:9200"
  ELASTICSEARCH_RECORDS_INDEX: "dmarc-records"
